name: trading_strategy_tester_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^6.2.1
  google_mobile_ads: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.2.2
  money_formatter: ^0.0.3
  list_ext: ^1.0.4
  currency_picker: ^2.0.11
  custom_slider: ^0.0.3
  skeleton_text: ^3.0.0
  card_loading: ^0.3.2
  tiny_charts: ^0.1.0
  fl_chart: ^0.71.0
  shared_preferences: ^2.0.15
  package_rename: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
