name: trading_strategy_tester_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  google_mobile_ads: ^1.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.2
  money_formatter: ^0.0.3
  list_ext: ^1.0.4
  currency_picker: ^2.0.11
  custom_slider: ^0.0.3
  slider_gradient: ^0.2.1
  skeleton_text: ^3.0.0
  card_loading: ^0.2.1
  tiny_charts: ^0.1.0
  fl_chart: ^0.55.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#3A0CA3"
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    color: "#3A0CA3"
    android: true
    web: true
    fullscreen: true

flutter:
  uses-material-design: true
